steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args: ["run", "deploy", "deunggiro-ocr", "--source=cloudrun", "--region=asia-northeast3", "--quiet"]
options:
  logging: CLOUD_LOGGING_ONLY
